pipewire: protocol: prevent panic when bubbling up an error
All other occurrences of self.on_connection_error() immediately return after it.

Returning early is vital, as `on_connection_error()` calls
```rust
        if let Some(source) = self.inner.source.write().unwrap().take() {
            let main_loop = self.core().context().main_loop();
            main_loop.destroy_source(source);
        }
```

and later in on_remote_data() we try to unwrap the `self.inner.source` Option.

Prevents this panic (triggered by a likely parsing bug in my branch, but this looks independently incorrect):
```
[T][23:04:45.897665] pw.connection | [   connection.rs:  338 TODO()] looking for message header from [1568..1600]
[T][23:04:45.897671] pw.connection | [   connection.rs:  207 TODO()] we need 1600, got header: true
[T][23:04:45.897675] pw.connection | [   connection.rs:  228 TODO()] got message id:3 opcode:0 seq:1709 size:16
[W][23:04:45.897687] pw.protocol  | [       client.rs:  305 TODO()] Got connection error: Custom { kind: InvalidData, error: "Could not decode message body: NoSpace" }
[T][23:04:45.897703] spa.loop     | [          loop.c: 1093 loop_destroy_source()] 0x586b11d08e80
[2025-12-10T22:04:45Z DEBUG tonari_pipewire] Got PipeWire Core error event, seq: 1708, res: 21, message: failed to read messages. Dropping the connection to PipeWire server to eventually reconnect and recover.
[T][23:04:45.897835] pw.connection | [   connection.rs:  207 TODO()] we need 16, got header: false
[T][23:04:45.897847] pw.connection | [   connection.rs:  175 TODO()] flushing 0 bytes

thread 'main' (3099) panicked at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/pipewire/src/protocol/client.rs:205:54:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/panicking.rs:145:5
   3: core::option::unwrap_failed
             at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/option.rs:2169:5
   4: core::option::Option<T>::unwrap
             at /home/tonari/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1010:21
   5: pipewire_native::protocol::client::Client::on_remote_data
             at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/pipewire/src/protocol/client.rs:205:54
   6: pipewire_native::protocol::client::Client::set_stream::{{closure}}
             at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/pipewire/src/protocol/client.rs:130:24
   7: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /home/tonari/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1992:9
   8: source_io_trampoline
             at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/spa/src/support/ffi/loop/utils.rs:116:9
   9: <unknown>
  10: pipewire_native_spa::support::ffi::loop::control::CLoopControlImpl::iterate
             at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/spa/src/support/ffi/loop/control.rs:207:30
  11: pipewire_native_spa::interface::loop::LoopControlImpl::iterate
             at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/spa/src/interface/loop.rs:120:9
  12: pipewire_native::main_loop::MainLoop::iterate
             at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/pipewire/src/main_loop.rs:208:41
  13: tonari_pipewire::PipeWireClient::iterate
             at ./src/lib.rs:88:14
  14: monitor_xruns::main
             at ./examples/monitor_xruns.rs:39:16
  15: core::ops::function::FnOnce::call_once
             at /home/tonari/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

thread 'main' (3099) panicked at library/core/src/panicking.rs:225:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x586b11ae74b2 - std::backtrace_rs::backtrace::libunwind::trace::hd6a158ff8b4ced9f
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:     0x586b11ae74b2 - std::backtrace_rs::backtrace::trace_unsynchronized::h92e289be85f564b0
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:     0x586b11ae74b2 - std::sys::backtrace::_print_fmt::h7593c35e5f3bf237
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/sys/backtrace.rs:66:9
   3:     0x586b11ae74b2 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::haa87a551a4affa55
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/sys/backtrace.rs:39:26
   4:     0x586b11af979f - core::fmt::rt::Argument::fmt::h4b16ed950bbe015d
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/fmt/rt.rs:173:76
   5:     0x586b11af979f - core::fmt::write::h80461e1e45e4fdd2
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/fmt/mod.rs:1468:25
   6:     0x586b11ab79b1 - std::io::default_write_fmt::h9e4845ee80fefc13
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/io/mod.rs:639:11
   7:     0x586b11ab79b1 - std::io::Write::write_fmt::h6e6c69b2d6337d9b
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/io/mod.rs:1954:13
   8:     0x586b11ac26e2 - std::sys::backtrace::BacktraceLock::print::hf67a46baa621998e
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/sys/backtrace.rs:42:9
   9:     0x586b11ac552c - std::panicking::default_hook::{{closure}}::h391aa815d5e47ec8
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:301:27
  10:     0x586b11ac5386 - std::panicking::default_hook::hd6fdcf2489bb807d
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:328:9
  11:     0x586b11ac5bb5 - std::panicking::panic_with_hook::h185ddfb86bf14d73
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:834:13
  12:     0x586b11ac5a16 - std::panicking::panic_handler::{{closure}}::had89ddd01b6112c9
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:700:13
  13:     0x586b11ac2819 - std::sys::backtrace::__rust_end_short_backtrace::h5d0fc36eef7265ea
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/sys/backtrace.rs:174:18
  14:     0x586b11aaba6d - __rustc[eb8946e36839644a]::rust_begin_unwind
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:698:5
  15:     0x586b11b02dfd - core::panicking::panic_nounwind_fmt::runtime::hecbbeaf03a90a418
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/panicking.rs:117:22
  16:     0x586b11b02dfd - core::panicking::panic_nounwind_fmt::h622822847ebd61be
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/intrinsics/mod.rs:2435:9
  17:     0x586b11b02d42 - core::panicking::panic_nounwind::h0b58b167cb35d9fe
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/panicking.rs:225:5
  18:     0x586b11b02f57 - core::panicking::panic_cannot_unwind::hebe3a4840b691755
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/panicking.rs:337:5
  19:     0x586b11927e7f - source_io_trampoline
                               at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/spa/src/support/ffi/loop/utils.rs:108:5
  20:     0x734483656d46 - <unknown>
  21:     0x586b1195ba5d - pipewire_native_spa::support::ffi::loop::control::CLoopControlImpl::iterate::h6ddd0e37670a3e7d
                               at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/spa/src/support/ffi/loop/control.rs:207:30
  22:     0x586b11942423 - pipewire_native_spa::interface::loop::LoopControlImpl::iterate::h23b8119001bb7fb2
                               at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/spa/src/interface/loop.rs:120:9
  23:     0x586b118194bf - pipewire_native::main_loop::MainLoop::iterate::h4b96f34d6744dd5f
                               at /home/tonari/.cargo/git/checkouts/pipewire-native-rs-c6307b8ea2550110/69c43dd/pipewire/src/main_loop.rs:208:41
  24:     0x586b117c8794 - tonari_pipewire::PipeWireClient::iterate::h99ed28483e6f488b
                               at /home/tonari/portal/crates/tonari-pipewire/src/lib.rs:88:14
  25:     0x586b117b5efb - monitor_xruns::main::h6aea33960b6df93b
                               at /home/tonari/portal/crates/tonari-pipewire/examples/monitor_xruns.rs:39:16
  26:     0x586b117bafbb - core::ops::function::FnOnce::call_once::h6e98c0358c149545
                               at /home/tonari/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  27:     0x586b117b8ecd - std::sys::backtrace::__rust_begin_short_backtrace::h11bf5cc021115e35
                               at /home/tonari/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:158:18
  28:     0x586b117ba471 - std::rt::lang_start::{{closure}}::hc4733e6eb5ee2319
                               at /home/tonari/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:206:18
  29:     0x586b11ab9770 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6bd8af1873a4fcba
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/core/src/ops/function.rs:287:21
  30:     0x586b11ab9770 - std::panicking::catch_unwind::do_call::h8502df911ab1d854
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:590:40
  31:     0x586b11ab9770 - std::panicking::catch_unwind::hf8590bd54a09e620
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:553:19
  32:     0x586b11ab9770 - std::panic::catch_unwind::hef0d4e02e13f8ea6
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panic.rs:359:14
  33:     0x586b11ab9770 - std::rt::lang_start_internal::{{closure}}::h013a94d4ae317bce
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/rt.rs:175:24
  34:     0x586b11ab9770 - std::panicking::catch_unwind::do_call::h0a1ac6ae8aee102d
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:590:40
  35:     0x586b11ab9770 - std::panicking::catch_unwind::hddd02d0cb4cfa799
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panicking.rs:553:19
  36:     0x586b11ab9770 - std::panic::catch_unwind::hbe5a97997afb148b
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/panic.rs:359:14
  37:     0x586b11ab9770 - std::rt::lang_start_internal::h6ba36b077a531782
                               at /rustc/ed61e7d7e242494fb7057f2657300d9e77bb4fcb/library/std/src/rt.rs:171:5
  38:     0x586b117ba457 - std::rt::lang_start::h2b3dd073bd8ecb97
                               at /home/tonari/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:205:5
  39:     0x586b117b672e - main
  40:     0x734483427675 - <unknown>
  41:     0x734483427729 - __libc_start_main
  42:     0x586b117b56c5 - _start
  43:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
```